version: '3.1'

services:
  ethermaria:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: eth
      MARIADB_USER: eth
      MARIADB_PASSWORD: eth
      MARIADB_DATABASE: eth
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "3306:3306"
